package DAO;

import Bean.STRACORDOSVELOZ;

public class O_ATUALIZAVELOZ {
	STRACORDOSVELOZ[] STRACORDOSVELOZ;

	public STRACORDOSVELOZ[] getSTRACORDOSVELOZ() {
		return STRACORDOSVELOZ;
	}

	public void setSTRACORDOSVELOZ(STRACORDOSVELOZ[] sTRACORDOSVELOZ) {
		STRACORDOSVELOZ = sTRACORDOSVELOZ;
	}
	
	
}
