package DAO;

import Bean.STRTITULOSVELOZ;

public class O_TITULOSVELOZ {
	STRTITULOSVELOZ[] STRTITULOSVELOZ;

	public STRTITULOSVELOZ[] getSTRTITULOSVELOZ() {
		return STRTITULOSVELOZ;
	}

	public void setSTRTITULOSVELOZ(STRTITULOSVELOZ[] sTRTITULOSVELOZ) {
		STRTITULOSVELOZ = sTRTITULOSVELOZ;
	}
	
	
}
